# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Название стадиона')),
                ('city', models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Город')),
                ('country', models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Страна')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Картинка стадиона')),
            ],
            options={
                'verbose_name_plural': 'стадионы',
                'verbose_name': 'стадион',
                'db_table': 'arena',
            },
        ),
        migrations.CreateModel(
            name='Cat_play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Тип игры')),
            ],
            options={
                'verbose_name_plural': 'Тип игр',
                'verbose_name': 'Тип игры',
                'db_table': 'cat_play',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Название игры')),
                ('is_home', models.BooleanField(verbose_name='Играем дома?')),
                ('date', models.DateTimeField(verbose_name='Дата игры')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Картинка игры')),
                ('cat_play', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Cat_play', verbose_name='Тип игры')),
            ],
            options={
                'verbose_name_plural': 'Игры',
                'verbose_name': 'Игра',
                'db_table': 'plays',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Название команды')),
                ('city', models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Город')),
                ('country', models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Страна')),
                ('gender', models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Пол игроков')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Герб команды')),
            ],
            options={
                'verbose_name_plural': 'Команды',
                'verbose_name': 'Команда',
                'db_table': 'teams',
            },
        ),
        migrations.AddField(
            model_name='play',
            name='enemy_team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enemy', to='content.Team', verbose_name='Команда противник'),
        ),
    ]
