# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20161024_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='place_game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arena', to='content.Arena', verbose_name='Место встречи'),
        ),
    ]
