# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_play_place_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='city',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='arena',
            name='country',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='arena',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Название стадиона'),
        ),
        migrations.AlterField(
            model_name='play',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='team',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Пол игроков'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Название команды'),
        ),
    ]
