# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20161024_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='enemy_team',
            field=models.ManyToManyField(blank=True, null=True, related_name='enemy', to='content.Team', verbose_name='Команда противник'),
        ),
        migrations.AddField(
            model_name='play',
            name='place_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='arena', to='content.Arena', verbose_name='Место встречи'),
        ),
    ]
