# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20161024_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['-date'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
    ]
