# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-08 20:10
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20161024_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250, verbose_name='Имя + Фамилия игрока')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Короткое описание игрока')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Полное описание игрока')),
                ('published', models.BooleanField(verbose_name='Опубликован')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Фото игрока')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Team', verbose_name='Команда игрока')),
            ],
            options={
                'verbose_name_plural': 'Игроки',
                'db_table': 'players',
                'verbose_name': 'Игрок',
                'ordering': ['ordering'],
            },
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['date'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
    ]
