# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-09 14:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20161108_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250, verbose_name='Название фото')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Короткое описание фото')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Полное описание фото')),
                ('published', models.BooleanField(verbose_name='Опубликован')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Фото')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name_plural': 'Фото',
                'ordering': ['-date'],
                'verbose_name': 'Фото',
                'db_table': 'photos',
            },
        ),
    ]
