# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-10 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_menuitem_cat_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='result',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='результат игры'),
        ),
        migrations.AddField(
            model_name='play',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='team', to='content.Team', verbose_name='Команда'),
        ),
    ]
